modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="ftbteamsfix"
version="1.0.0"
displayName="FTB Teams Offline Enabler"
description="Fixes offline UUID detection for FTB Teams on NeoForge."

[[mixins]]
config="ftbteamsfix.mixins.json"
